language: node_js
node_js:
  - 13
services:
  - docker
script:
  - docker build -t simple-node-v2 .
  - docker tag simple-node-v2 pthhhhhh/cloud-travis-p3:latest
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push pthhhhhh/cloud-travis-p3
